const listData = [
    {
    amenities: "Furnished",
    image: "Img1.jpg",
    price: "Rp.9.000.000",
    rent: "Year",
    property: "3 Beds, 2 Bats, 1,800 sqft",
    addres: "Tangerang Selatan, Pondok Aren",
    },
    {
    amenities: "Furnished",
    image: "Img2.jpg",
    price: "Rp.3.000.000",
    rent: "Year",
    property: "1 Beds, 1 Bats, 800 sqft",
    addres: "Tangerang Selatan, Pondok Aren",
    },
    {
    amenities: "Furnished",
    image: "Img3.jpg",
    price: "Rp.5.000.000",
    rent: "Year",
    property: "2 Beds, 1 Bats, 1,200 sqft",
    addres: "Tangerang Selatan, Pondok Aren",
    },
    {
    amenities: "Furnished",
    image: "Img4.jpg",
    price: "Rp.13.000.000",
    rent: "Year",
    property: "4 Beds, 3 Bats, 2,200 sqft",
    addres: "Tangerang Selatan, Pondok Aren",
    },
    {
    amenities: "Furnished",
    image: "Img5.jpg",
    price: "Rp.3.500.000",
    rent: "Year",
    property: "1 Beds, 1 Bats, 810 sqft",
    addres: "Tangerang Selatan, Pondok Aren",
    },
    {
    amenities: "Furnished",
    image: "Img6.jpg",
    price: "Rp.5.500.000",
    rent: "Year",
    property: "2 Beds, 2 Bats, 1,900 sqft",
    addres: "Tangerang Selatan, Pondok Aren",
    },
    {
    amenities: "Furnished",
    image: "Img7.jpg",
    price: "Rp.13.000.000",
    rent: "Year",
    property: "4 Beds, 3 Bats, 2,200 sqft",
    addres: "Tangerang Selatan, Pondok Aren",
    },
    {
    amenities: "Furnished",
    image: "Img8.jpg",
    price: "Rp.3.500.000",
    rent: "Year",
    property: "1 Beds, 1 Bats, 810 sqft",
    addres: "Tangerang Selatan, Pondok Aren",
    },
    {
    amenities: "Furnished",
    image: "Img9.jpg",
    price: "Rp.5.500.000",
    rent: "Year",
    property: "2 Beds, 2 Bats, 1,900 sqft",
    addres: "Tangerang Selatan, Pondok Aren",
    },
]

export default listData;